# Generated by Django 6.0.3 on 2026-03-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_report_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='upload_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
